cloud:
  aws:
    credentials:
      access-key: *
      secret-key: *
    region:
      static: eu-north-1
    stack:
      auto: false

application:
  bucket:
    name: nnjavateachie

server:
  port: 9090